spring:

  datasource:
     url: jdbc:mysql://localhost:3306/BD-Degree
     username: root
     password: 1234

  jpa:
   show-sql: true
   hibernate:
     ddl-auto: update
     naming:
       strategy: org.hibernate.cfg.ImprovedNaming.Strategy

  properties:
   dialect:org.hibernate.dialect.MySQL5Dialect
